// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: kremind.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reminders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminders []*Reminder `protobuf:"bytes,1,rep,name=reminders,proto3" json:"reminders,omitempty"`
}

func (x *Reminders) Reset() {
	*x = Reminders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kremind_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reminders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reminders) ProtoMessage() {}

func (x *Reminders) ProtoReflect() protoreflect.Message {
	mi := &file_kremind_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reminders.ProtoReflect.Descriptor instead.
func (*Reminders) Descriptor() ([]byte, []int) {
	return file_kremind_proto_rawDescGZIP(), []int{0}
}

func (x *Reminders) GetReminders() []*Reminder {
	if x != nil {
		return x.Reminders
	}
	return nil
}

type Reminder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime       int64  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	RepeatInSeconds int64  `protobuf:"varint,3,opt,name=repeat_in_seconds,json=repeatInSeconds,proto3" json:"repeat_in_seconds,omitempty"`
	LastRunTime     int64  `protobuf:"varint,4,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time,omitempty"`
	Reminder        string `protobuf:"bytes,5,opt,name=reminder,proto3" json:"reminder,omitempty"`
	Source          string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Current         int32  `protobuf:"varint,7,opt,name=current,proto3" json:"current,omitempty"`
	LastFailure     string `protobuf:"bytes,8,opt,name=last_failure,json=lastFailure,proto3" json:"last_failure,omitempty"`
}

func (x *Reminder) Reset() {
	*x = Reminder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kremind_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reminder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reminder) ProtoMessage() {}

func (x *Reminder) ProtoReflect() protoreflect.Message {
	mi := &file_kremind_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reminder.ProtoReflect.Descriptor instead.
func (*Reminder) Descriptor() ([]byte, []int) {
	return file_kremind_proto_rawDescGZIP(), []int{1}
}

func (x *Reminder) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reminder) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Reminder) GetRepeatInSeconds() int64 {
	if x != nil {
		return x.RepeatInSeconds
	}
	return 0
}

func (x *Reminder) GetLastRunTime() int64 {
	if x != nil {
		return x.LastRunTime
	}
	return 0
}

func (x *Reminder) GetReminder() string {
	if x != nil {
		return x.Reminder
	}
	return ""
}

func (x *Reminder) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Reminder) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Reminder) GetLastFailure() string {
	if x != nil {
		return x.LastFailure
	}
	return ""
}

type AddReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime       int64  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	RepeatInSeconds int64  `protobuf:"varint,2,opt,name=repeat_in_seconds,json=repeatInSeconds,proto3" json:"repeat_in_seconds,omitempty"`
	Reminder        string `protobuf:"bytes,3,opt,name=reminder,proto3" json:"reminder,omitempty"`
	Source          string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *AddReminderRequest) Reset() {
	*x = AddReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kremind_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReminderRequest) ProtoMessage() {}

func (x *AddReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kremind_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReminderRequest.ProtoReflect.Descriptor instead.
func (*AddReminderRequest) Descriptor() ([]byte, []int) {
	return file_kremind_proto_rawDescGZIP(), []int{2}
}

func (x *AddReminderRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AddReminderRequest) GetRepeatInSeconds() int64 {
	if x != nil {
		return x.RepeatInSeconds
	}
	return 0
}

func (x *AddReminderRequest) GetReminder() string {
	if x != nil {
		return x.Reminder
	}
	return ""
}

func (x *AddReminderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type AddReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddReminderResponse) Reset() {
	*x = AddReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kremind_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReminderResponse) ProtoMessage() {}

func (x *AddReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kremind_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReminderResponse.ProtoReflect.Descriptor instead.
func (*AddReminderResponse) Descriptor() ([]byte, []int) {
	return file_kremind_proto_rawDescGZIP(), []int{3}
}

func (x *AddReminderResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRemindersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampSeconds int64 `protobuf:"varint,1,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
}

func (x *ListRemindersRequest) Reset() {
	*x = ListRemindersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kremind_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRemindersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemindersRequest) ProtoMessage() {}

func (x *ListRemindersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kremind_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemindersRequest.ProtoReflect.Descriptor instead.
func (*ListRemindersRequest) Descriptor() ([]byte, []int) {
	return file_kremind_proto_rawDescGZIP(), []int{4}
}

func (x *ListRemindersRequest) GetTimestampSeconds() int64 {
	if x != nil {
		return x.TimestampSeconds
	}
	return 0
}

type ListRemindersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reminders []*Reminder `protobuf:"bytes,1,rep,name=reminders,proto3" json:"reminders,omitempty"`
}

func (x *ListRemindersResponse) Reset() {
	*x = ListRemindersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kremind_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRemindersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemindersResponse) ProtoMessage() {}

func (x *ListRemindersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kremind_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemindersResponse.ProtoReflect.Descriptor instead.
func (*ListRemindersResponse) Descriptor() ([]byte, []int) {
	return file_kremind_proto_rawDescGZIP(), []int{5}
}

func (x *ListRemindersResponse) GetReminders() []*Reminder {
	if x != nil {
		return x.Reminders
	}
	return nil
}

type DeleteReinderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteReinderRequest) Reset() {
	*x = DeleteReinderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kremind_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReinderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReinderRequest) ProtoMessage() {}

func (x *DeleteReinderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kremind_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReinderRequest.ProtoReflect.Descriptor instead.
func (*DeleteReinderRequest) Descriptor() ([]byte, []int) {
	return file_kremind_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReinderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteReminderResponse) Reset() {
	*x = DeleteReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kremind_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReminderResponse) ProtoMessage() {}

func (x *DeleteReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kremind_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReminderResponse.ProtoReflect.Descriptor instead.
func (*DeleteReminderResponse) Descriptor() ([]byte, []int) {
	return file_kremind_proto_rawDescGZIP(), []int{7}
}

var File_kremind_proto protoreflect.FileDescriptor

var file_kremind_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x22, 0x3c, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x72, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x22, 0xfa, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x5f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x22,
	0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x75, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x75, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x46, 0x61, 0x69, 0x6c,
	0x75, 0x72, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x72, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x49, 0x6e, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x41, 0x64, 0x64,
	0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x43, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x48, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x09, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x22,
	0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0x82, 0x02, 0x0a, 0x0e, 0x4b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x52, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x50, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x1d, 0x2e, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x52, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2f, 0x6b, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kremind_proto_rawDescOnce sync.Once
	file_kremind_proto_rawDescData = file_kremind_proto_rawDesc
)

func file_kremind_proto_rawDescGZIP() []byte {
	file_kremind_proto_rawDescOnce.Do(func() {
		file_kremind_proto_rawDescData = protoimpl.X.CompressGZIP(file_kremind_proto_rawDescData)
	})
	return file_kremind_proto_rawDescData
}

var file_kremind_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kremind_proto_goTypes = []interface{}{
	(*Reminders)(nil),              // 0: kremind.Reminders
	(*Reminder)(nil),               // 1: kremind.Reminder
	(*AddReminderRequest)(nil),     // 2: kremind.AddReminderRequest
	(*AddReminderResponse)(nil),    // 3: kremind.AddReminderResponse
	(*ListRemindersRequest)(nil),   // 4: kremind.ListRemindersRequest
	(*ListRemindersResponse)(nil),  // 5: kremind.ListRemindersResponse
	(*DeleteReinderRequest)(nil),   // 6: kremind.DeleteReinderRequest
	(*DeleteReminderResponse)(nil), // 7: kremind.DeleteReminderResponse
}
var file_kremind_proto_depIdxs = []int32{
	1, // 0: kremind.Reminders.reminders:type_name -> kremind.Reminder
	1, // 1: kremind.ListRemindersResponse.reminders:type_name -> kremind.Reminder
	2, // 2: kremind.KremindService.AddReminder:input_type -> kremind.AddReminderRequest
	4, // 3: kremind.KremindService.ListReminders:input_type -> kremind.ListRemindersRequest
	6, // 4: kremind.KremindService.DeleteReminder:input_type -> kremind.DeleteReinderRequest
	3, // 5: kremind.KremindService.AddReminder:output_type -> kremind.AddReminderResponse
	5, // 6: kremind.KremindService.ListReminders:output_type -> kremind.ListRemindersResponse
	7, // 7: kremind.KremindService.DeleteReminder:output_type -> kremind.DeleteReminderResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kremind_proto_init() }
func file_kremind_proto_init() {
	if File_kremind_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kremind_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reminders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kremind_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reminder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kremind_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kremind_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kremind_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRemindersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kremind_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRemindersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kremind_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReinderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kremind_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kremind_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kremind_proto_goTypes,
		DependencyIndexes: file_kremind_proto_depIdxs,
		MessageInfos:      file_kremind_proto_msgTypes,
	}.Build()
	File_kremind_proto = out.File
	file_kremind_proto_rawDesc = nil
	file_kremind_proto_goTypes = nil
	file_kremind_proto_depIdxs = nil
}
